name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule: 
    # Runs at every 12AM UTC
    - cron: '0 0 * * *' 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://neelanjan.dev/feed.xml"
          max_post_count: 4
